"""ASocksLib — Python library and CLI for the ASocks Proxy API."""

from __future__ import annotations

from asockslib.benchmark import (
    CountryPingResult,
    FindBestResult,
    ProxyBenchmarkResult,
    benchmark_proxies,
    find_best_proxies,
    ping_proxy,
    select_best_proxies,
)
from asockslib.client import ASocksClient
from asockslib.exceptions import (
    APIConnectionError,
    ASocksError,
    AuthenticationError,
    InsufficientBalanceError,
    NoAvailableProxyError,
    PortNotFoundError,
    ProxyHealthError,
    RateLimitError,
)
from asockslib.geo_picker import (
    GeoPicker,
    PickedASN,
    PickedCity,
    PickedConnectionType,
    PickedCountry,
    PickedProxyType,
    PickedServerPortType,
    PickedState,
)
from asockslib.models import (
    ASNInfo,
    ASNListResponse,
    AuthType,
    BalanceResponse,
    CityInfo,
    ConnectionType,
    ConnectionTypeId,
    CountryInfo,
    CreatePortRequest,
    CreateTemplateRequest,
    PortFilterParams,
    PortInfo,
    PortListResponse,
    PortStatus,
    ProxyType,
    ProxyTypeId,
    ServerPortType,
    StateInfo,
    UpdatePortRequest,
    UpdateTemplateRequest,
)
from asockslib.proxy_pool import PoolStrategy, ProxyPool, ProxyPoolStats, ProxyStore
from asockslib.quick import get_proxies, get_proxies_sync
from asockslib.smart_proxy import SmartProxy

__all__ = [
    "APIConnectionError",
    "ASNInfo",
    "ASNListResponse",
    "ASocksClient",
    "ASocksError",
    "AuthType",
    "AuthenticationError",
    "BalanceResponse",
    "CityInfo",
    "ConnectionType",
    "ConnectionTypeId",
    "CountryInfo",
    "CountryPingResult",
    "CreatePortRequest",
    "CreateTemplateRequest",
    "FindBestResult",
    "GeoPicker",
    "InsufficientBalanceError",
    "NoAvailableProxyError",
    "PickedASN",
    "PickedCity",
    "PickedConnectionType",
    "PickedCountry",
    "PickedProxyType",
    "PickedServerPortType",
    "PickedState",
    "PoolStrategy",
    "PortFilterParams",
    "PortInfo",
    "PortListResponse",
    "PortNotFoundError",
    "PortStatus",
    "ProxyBenchmarkResult",
    "ProxyHealthError",
    "ProxyPool",
    "ProxyPoolStats",
    "ProxyStore",
    "ProxyType",
    "ProxyTypeId",
    "RateLimitError",
    "ServerPortType",
    "SmartProxy",
    "StateInfo",
    "UpdatePortRequest",
    "UpdateTemplateRequest",
    "benchmark_proxies",
    "find_best_proxies",
    "get_proxies",
    "get_proxies_sync",
    "ping_proxy",
    "select_best_proxies",
]

__version__ = "0.1.1"
